name: Automation Tests

on:
  workflow_dispatch: # Untuk manual trigger
  pull_request:     # Otomatis berjalan saat ada PR ke main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run API Tests
        run: ./gradlew cucumberTest -Ptags="@api"

      - name: Run Web UI Tests
        run: ./gradlew cucumberTest -Ptags="@web"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/cucumber/
