name: Run Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run API Tests
        run: ./gradlew test -Dcucumber.filter.tags="@api"

      - name: Run Web UI Tests
        run: ./gradlew test -Dcucumber.filter.tags="@web"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/cucumber/
