name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install ChromeDriver
        run: |
            CHROME_MAJOR_VERSION=$(google-chrome --version | sed -E 's/Google Chrome ([0-9]+)\..*/\1/')
            echo "Chrome Major Version: $CHROME_MAJOR_VERSION"
            DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")
            echo "ChromeDriver Version: $DRIVER_VERSION"
            if [[ -z "$DRIVER_VERSION" ]]; then
              echo "Failed to fetch ChromeDriver version based on major version. Trying latest stable."
              DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
              echo "ChromeDriver Version (Latest Stable): $DRIVER_VERSION"
            fi
            wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/

      - name: Grant permission to execute gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -Dchromeoptions.args="--headless --no-sandbox"