name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          echo "ChromeDriver Version (Latest Stable): $DRIVER_VERSION"
          wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Verify ChromeDriver Permissions
        run: |
          ls -l /usr/local/bin/chromedriver

      - name: Grant permission to execute gradlew
        run: chmod +x ./gradlew

      - name: Run Tests (Without Headless)
        run: ./gradlew test -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver