name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Chrome dan Chromedriver versi kompatibel
        run: |
            # Install Chrome versi 114 (stabil & tersedia ChromeDriver-nya)
            sudo apt-get update
            wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.133-1_amd64.deb
            sudo apt install -y ./google-chrome-stable_114.0.5735.133-1_amd64.deb
        
            # Download ChromeDriver versi yang cocok
            wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
        

      - name: Grant permission to execute gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test -Dchromeoptions.args="--headless --no-sandbox"
