name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver
        uses: actions/setup-chromedriver@v3 # Menambahkan ChromeDriver installation
        with:
          chrome-version: stable # Memastikan versi ChromeDriver sesuai dengan Chrome

      - name: Grant permission to execute gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test -Dchromeoptions.args="--headless --no-sandbox" # Menambahkan opsi headless dan no-sandbox