name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Update PATH (Try 1)
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Find ChromeDriver
        run: find $GITHUB_WORKSPACE -name "chromedriver" -print

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test -Dchromeoptions.args="--headless=new --no-sandbox --disable-dev-shm-usage"